// 테마 정본 — 팔레트 객체 하나 추가 = 테마 하나 추가 (docs/THEME_SYSTEM.md)
// hex는 docs/design/theme-mockups-10.png 시안에서 추출한 근사값. 실기기 대조로 조정한다.
// 컴포넌트는 색상 리터럴 금지 — 이 토큰만 참조한다.

export const THEME_IDS = [
  'minimalLight',
  'darkModern',
  'natureGreen',
  'skyBlue',
  'warmBeige',
  'neonCyber',
  'carbonGray',
  'pastelLavender',
  'yellowPoint',
  'oceanDeep',
] as const;

export type ThemeId = (typeof THEME_IDS)[number];

export const DEFAULT_THEME_ID: ThemeId = 'minimalLight';

export interface ThemePalette {
  id: ThemeId;
  isDark: boolean; // 상태바·헤더 콘텐츠 스타일 파생
  background: string;
  surface: string;
  card: string;
  searchBar: string;
  primary: string;
  secondary: string;
  text: string;
  textMuted: string;
  icon: string;
  button: string;
  buttonText: string;
  navigation: string;
  navigationActive: string;
  selected: string;
  favoriteArea: string;
  badge: string;
  badgeText: string;
  border: string;
}

export const THEMES: Record<ThemeId, ThemePalette> = {
  minimalLight: {
    id: 'minimalLight',
    isDark: false,
    background: '#FFFFFF',
    surface: '#F5F6F8',
    card: '#FFFFFF',
    searchBar: '#F1F3F5',
    primary: '#2563EB',
    secondary: '#6B7280',
    text: '#111827',
    textMuted: '#6B7280',
    icon: '#374151',
    button: '#2563EB',
    buttonText: '#FFFFFF',
    navigation: '#FFFFFF',
    navigationActive: '#2563EB',
    selected: '#EFF6FF',
    favoriteArea: '#FFFFFF',
    badge: '#F3F4F6',
    badgeText: '#374151',
    border: '#E5E7EB',
  },
  darkModern: {
    id: 'darkModern',
    isDark: true,
    background: '#121214',
    surface: '#1A1A1E',
    card: '#232327',
    searchBar: '#232327',
    primary: '#3B82F6',
    secondary: '#9CA3AF',
    text: '#F3F4F6',
    textMuted: '#9CA3AF',
    icon: '#D1D5DB',
    button: '#3B82F6',
    buttonText: '#FFFFFF',
    navigation: '#1A1A1E',
    navigationActive: '#3B82F6',
    selected: '#1E2A45',
    favoriteArea: '#232327',
    badge: '#2E2E33',
    badgeText: '#D1D5DB',
    border: '#2E2E33',
  },
  natureGreen: {
    id: 'natureGreen',
    isDark: false,
    background: '#FFFFFF',
    surface: '#F2F8F0',
    card: '#E9F4E5',
    searchBar: '#F0F6EC',
    primary: '#35A554',
    secondary: '#5C7060',
    text: '#1B2E1F',
    textMuted: '#5C7060',
    icon: '#3C5A44',
    button: '#35A554',
    buttonText: '#FFFFFF',
    navigation: '#FFFFFF',
    navigationActive: '#35A554',
    selected: '#DFF0DA',
    favoriteArea: '#E9F4E5',
    badge: '#E3EFDF',
    badgeText: '#3C5A44',
    border: '#DCEAD6',
  },
  skyBlue: {
    id: 'skyBlue',
    isDark: false,
    background: '#EAF4FE',
    surface: '#F3F9FF',
    card: '#DFEEFB',
    searchBar: '#FFFFFF',
    primary: '#2E90FA',
    secondary: '#51708C',
    text: '#0F2A43',
    textMuted: '#51708C',
    icon: '#2A5B85',
    button: '#2E90FA',
    buttonText: '#FFFFFF',
    navigation: '#F3F9FF',
    navigationActive: '#2E90FA',
    selected: '#D2E7FA',
    favoriteArea: '#DFEEFB',
    badge: '#D9EAF9',
    badgeText: '#2A5B85',
    border: '#CFE4F7',
  },
  warmBeige: {
    id: 'warmBeige',
    isDark: false,
    background: '#F8F2E7',
    surface: '#F3EBDD',
    card: '#EFE4D2',
    searchBar: '#F1E9DA',
    primary: '#8B6844',
    secondary: '#7C6E5C',
    text: '#3E3225',
    textMuted: '#7C6E5C',
    icon: '#6B573F',
    button: '#8B6844',
    buttonText: '#FFFFFF',
    navigation: '#F3EBDD',
    navigationActive: '#8B6844',
    selected: '#EADFC9',
    favoriteArea: '#EFE4D2',
    badge: '#E8DCC6',
    badgeText: '#6B573F',
    border: '#E4D8C2',
  },
  neonCyber: {
    id: 'neonCyber',
    isDark: true,
    background: '#0B0812',
    surface: '#140F1D',
    card: '#191223',
    searchBar: '#191223',
    primary: '#E93DF0',
    secondary: '#A18FC0',
    text: '#F4EBFF',
    textMuted: '#A18FC0',
    icon: '#D9B8F5',
    button: '#E93DF0',
    buttonText: '#FFFFFF',
    navigation: '#140F1D',
    navigationActive: '#E93DF0',
    selected: '#2A1638',
    favoriteArea: '#191223',
    badge: '#241733',
    badgeText: '#D9B8F5',
    border: '#3A2050',
  },
  carbonGray: {
    id: 'carbonGray',
    isDark: true,
    background: '#26282C',
    surface: '#2E3136',
    card: '#35383E',
    searchBar: '#35383E',
    primary: '#9CA3AB',
    secondary: '#9CA3AB',
    text: '#E8EAED',
    textMuted: '#9CA3AB',
    icon: '#C3C7CD',
    button: '#565B63',
    buttonText: '#FFFFFF',
    navigation: '#2E3136',
    navigationActive: '#E8EAED',
    selected: '#3E424A',
    favoriteArea: '#35383E',
    badge: '#40444B',
    badgeText: '#C3C7CD',
    border: '#40444B',
  },
  pastelLavender: {
    id: 'pastelLavender',
    isDark: false,
    background: '#F5F1FC',
    surface: '#EFE8FA',
    card: '#E9E0F8',
    searchBar: '#FFFFFF',
    primary: '#8B5CF6',
    secondary: '#6E6288',
    text: '#2E2440',
    textMuted: '#6E6288',
    icon: '#5E4B85',
    button: '#8B5CF6',
    buttonText: '#FFFFFF',
    navigation: '#EFE8FA',
    navigationActive: '#8B5CF6',
    selected: '#E0D2F5',
    favoriteArea: '#E9E0F8',
    badge: '#E4D9F4',
    badgeText: '#5E4B85',
    border: '#DFD3F0',
  },
  yellowPoint: {
    id: 'yellowPoint',
    isDark: false,
    background: '#FFFFFF',
    surface: '#FFFBEF',
    card: '#FFF4D6',
    searchBar: '#F7F7F5',
    primary: '#E0A800',
    secondary: '#6E6650',
    text: '#201A0A',
    textMuted: '#6E6650',
    icon: '#4E4630',
    button: '#F5B800',
    buttonText: '#201A0A', // 옐로우 버튼은 흰 글자가 안 읽힌다 — 다크 텍스트
    navigation: '#FFFFFF',
    navigationActive: '#E0A800',
    selected: '#FFF0C2',
    favoriteArea: '#FFF4D6',
    badge: '#FCEFC7',
    badgeText: '#6E5A1E',
    border: '#F0E6C8',
  },
  oceanDeep: {
    id: 'oceanDeep',
    isDark: true,
    background: '#0A182E',
    surface: '#0F2140',
    card: '#142A4E',
    searchBar: '#142A4E',
    primary: '#3D8BFD',
    secondary: '#8FA8C7',
    text: '#E9F1FB',
    textMuted: '#8FA8C7',
    icon: '#BBD0E8',
    button: '#3D8BFD',
    buttonText: '#FFFFFF',
    navigation: '#0F2140',
    navigationActive: '#3D8BFD',
    selected: '#1C3866',
    favoriteArea: '#142A4E',
    badge: '#1B3358',
    badgeText: '#BBD0E8',
    border: '#1E3A63',
  },
};
